package com.grselectronics.inventario.bean;
// Generated 20-jun-2016 15:36:15 by Hibernate Tools 4.3.1



/**
 * AsignacionEquipo generated by hbm2java
 */
public class AsignacionEquipo  implements java.io.Serializable {


     private Integer idAsignacionEquipo;
     private Departamento departamento;
     private Empleado empleado;
     private Equipo equipo;
     private Usuario usuario;
     private String fechaAsignacion;
     private String fechaEntrega;

    public AsignacionEquipo() {
    }

    public AsignacionEquipo(Departamento departamento, Empleado empleado, Equipo equipo, Usuario usuario, String fechaAsignacion, String fechaEntrega) {
       this.departamento = departamento;
       this.empleado = empleado;
       this.equipo = equipo;
       this.usuario = usuario;
       this.fechaAsignacion = fechaAsignacion;
       this.fechaEntrega = fechaEntrega;
    }
   
    public Integer getIdAsignacionEquipo() {
        return this.idAsignacionEquipo;
    }
    
    public void setIdAsignacionEquipo(Integer idAsignacionEquipo) {
        this.idAsignacionEquipo = idAsignacionEquipo;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(String fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public String getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(String fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }




}


