package com.grselectronics.inventario.bean;
// Generated 20-jun-2016 15:36:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Caracteristica generated by hbm2java
 */
public class Caracteristica  implements java.io.Serializable {


     private Integer idCaracteristica;
     private String nombre;
     private String descripcion;
     private Set caracteristicaEquipos = new HashSet(0);

    public Caracteristica() {
    }

    public Caracteristica(String nombre, String descripcion, Set caracteristicaEquipos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.caracteristicaEquipos = caracteristicaEquipos;
    }
   
    public Integer getIdCaracteristica() {
        return this.idCaracteristica;
    }
    
    public void setIdCaracteristica(Integer idCaracteristica) {
        this.idCaracteristica = idCaracteristica;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCaracteristicaEquipos() {
        return this.caracteristicaEquipos;
    }
    
    public void setCaracteristicaEquipos(Set caracteristicaEquipos) {
        this.caracteristicaEquipos = caracteristicaEquipos;
    }




}


