package com.grselectronics.inventario.bean;
// Generated 16/06/2016 10:19:16 AM by Hibernate Tools 4.3.1



/**
 * CaracteristicaEquipo generated by hbm2java
 */
public class CaracteristicaEquipo  implements java.io.Serializable {


     private Integer idCaracteristicaEquipo;
     private Caracteristica caracteristica;
     private Equipo equipo;

    public CaracteristicaEquipo() {
    }

    public CaracteristicaEquipo(Caracteristica caracteristica, Equipo equipo) {
       this.caracteristica = caracteristica;
       this.equipo = equipo;
    }
   
    public Integer getIdCaracteristicaEquipo() {
        return this.idCaracteristicaEquipo;
    }
    
    public void setIdCaracteristicaEquipo(Integer idCaracteristicaEquipo) {
        this.idCaracteristicaEquipo = idCaracteristicaEquipo;
    }
    public Caracteristica getCaracteristica() {
        return this.caracteristica;
    }
    
    public void setCaracteristica(Caracteristica caracteristica) {
        this.caracteristica = caracteristica;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }




}


