package com.grselectronics.inventario.bean;
// Generated 20-jun-2016 15:36:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Empresa empresa;
     private Estado estado;
     private Tipo tipo;
     private String marca;
     private String modelo;
     private String numSerie;
     private String ubicacion;
     private String fechaCompra;
     private String finGarantia;
     private String tiempoDeVida;
     private String estadoDeGarantia;
     private String ip;
     private String macAddress;
     private String userActivedirectory;
     private String hostName;
     private String licencia;
     private String os;
     private Set asignacionEquipos = new HashSet(0);
     private Set caracteristicaEquipos = new HashSet(0);

    public Equipo() {
    }

    public Equipo(Empresa empresa, Estado estado, Tipo tipo, String marca, String modelo, String numSerie, String ubicacion, String fechaCompra, String finGarantia, String tiempoDeVida, String estadoDeGarantia, String ip, String macAddress, String userActivedirectory, String hostName, String licencia, String os) {
       this.empresa = empresa;
       this.estado = estado;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.numSerie = numSerie;
       this.ubicacion = ubicacion;
       this.fechaCompra = fechaCompra;
       this.finGarantia = finGarantia;
       this.tiempoDeVida = tiempoDeVida;
       this.estadoDeGarantia = estadoDeGarantia;
       this.ip = ip;
       this.macAddress = macAddress;
       this.userActivedirectory = userActivedirectory;
       this.hostName = hostName;
       this.licencia = licencia;
       this.os = os;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getFinGarantia() {
        return this.finGarantia;
    }
    
    public void setFinGarantia(String finGarantia) {
        this.finGarantia = finGarantia;
    }
    public String getTiempoDeVida() {
        return this.tiempoDeVida;
    }
    
    public void setTiempoDeVida(String tiempoDeVida) {
        this.tiempoDeVida = tiempoDeVida;
    }
    public String getEstadoDeGarantia() {
        return this.estadoDeGarantia;
    }
    
    public void setEstadoDeGarantia(String estadoDeGarantia) {
        this.estadoDeGarantia = estadoDeGarantia;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    public String getUserActivedirectory() {
        return this.userActivedirectory;
    }
    
    public void setUserActivedirectory(String userActivedirectory) {
        this.userActivedirectory = userActivedirectory;
    }
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    public Set getAsignacionEquipos() {
        return this.asignacionEquipos;
    }
    
    public void setAsignacionEquipos(Set asignacionEquipos) {
        this.asignacionEquipos = asignacionEquipos;
    }
    public Set getCaracteristicaEquipos() {
        return this.caracteristicaEquipos;
    }
    
    public void setCaracteristicaEquipos(Set caracteristicaEquipos) {
        this.caracteristicaEquipos = caracteristicaEquipos;
    }




}


