package com.grselectronics.inventario.bean;
// Generated 16/06/2016 10:19:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Empresa empresa;
     private Estado estado;
     private Tipo tipo;
     private String marca;
     private String modelo;
     private String numSerie;
     private String ubicacion;
     private String fechaCompra;
     private String finGarantia;
     private String tiempoDeVida;
     private String estadoDeGarantia;
     private Set asignacionEquipos = new HashSet(0);
     private Set caracteristicaEquipos = new HashSet(0);

    public Equipo() {
    }

    public Equipo(Empresa empresa, Estado estado, Tipo tipo, String marca, String modelo, String numSerie, String ubicacion, String fechaCompra, String finGarantia, String tiempoDeVida, String estadoDeGarantia, Set asignacionEquipos, Set caracteristicaEquipos) {
       this.empresa = empresa;
       this.estado = estado;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.numSerie = numSerie;
       this.ubicacion = ubicacion;
       this.fechaCompra = fechaCompra;
       this.finGarantia = finGarantia;
       this.tiempoDeVida = tiempoDeVida;
       this.estadoDeGarantia = estadoDeGarantia;
       this.asignacionEquipos = asignacionEquipos;
       this.caracteristicaEquipos = caracteristicaEquipos;
    }
   
    public Equipo(Empresa empresa, Estado estado, Tipo tipo, String marca, String modelo, String numSerie, String ubicacion, String fechaCompra, String finGarantia, String tiempoDeVida, String estadoDeGarantia) {
       this.empresa = empresa;
       this.estado = estado;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.numSerie = numSerie;
       this.ubicacion = ubicacion;
       this.fechaCompra = fechaCompra;
       this.finGarantia = finGarantia;
       this.tiempoDeVida = tiempoDeVida;
       this.estadoDeGarantia = estadoDeGarantia;
    }
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getFinGarantia() {
        return this.finGarantia;
    }
    
    public void setFinGarantia(String finGarantia) {
        this.finGarantia = finGarantia;
    }
    public String getTiempoDeVida() {
        return this.tiempoDeVida;
    }
    
    public void setTiempoDeVida(String tiempoDeVida) {
        this.tiempoDeVida = tiempoDeVida;
    }
    public String getEstadoDeGarantia() {
        return this.estadoDeGarantia;
    }
    
    public void setEstadoDeGarantia(String estadoDeGarantia) {
        this.estadoDeGarantia = estadoDeGarantia;
    }
    public Set getAsignacionEquipos() {
        return this.asignacionEquipos;
    }
    
    public void setAsignacionEquipos(Set asignacionEquipos) {
        this.asignacionEquipos = asignacionEquipos;
    }
    public Set getCaracteristicaEquipos() {
        return this.caracteristicaEquipos;
    }
    
    public void setCaracteristicaEquipos(Set caracteristicaEquipos) {
        this.caracteristicaEquipos = caracteristicaEquipos;
    }




}


