package com.grselectronics.inventario.bean;
// Generated 20-jun-2016 15:36:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private String nommbre;
     private Set empresas = new HashSet(0);

    public Pais() {
    }

    public Pais(String nommbre, Set empresas) {
       this.nommbre = nommbre;
       this.empresas = empresas;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNommbre() {
        return this.nommbre;
    }
    
    public void setNommbre(String nommbre) {
        this.nommbre = nommbre;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


